Repository SE701-T1/backend, pull requests merged in 2022-03, with the labels that each got.

#6 Create Contributing Guidelines file
  CONTRIBUTING.md
Labels: Type: Documentation

#5 Adding the PR template.
  .github/pull_request_template.md
Labels: Type: Documentation

#7 Docs: Code of Conduct Backend
  CODE_OF_CONDUCT.md
Labels: Type: Documentation

#14 Basic endpoint
  pom.xml
  src/main/java/com/team701/buddymatcher/controllers/BasicController.java
  src/main/java/com/team701/buddymatcher/services/BasicService.java
  src/main/java/com/team701/buddymatcher/services/impl/BasicServiceImpl.java
  src/main/resources/application.properties
Labels: Priority: Medium, Status: Review Needed, Type: Feature

#46 Refactor Pair entity to Buddies
  src/main/java/com/team701/buddymatcher/domain/users/Buddies.java
  src/main/java/com/team701/buddymatcher/domain/users/User.java
  src/main/java/com/team701/buddymatcher/dtos/users/BuddiesDTO.java
  src/main/java/com/team701/buddymatcher/dtos/users/UserDTO.java
  src/main/resources/schema.sql
  src/test/java/com/team701/buddymatcher/controllers/users/UserControllerUnitTest.java
  src/test/java/com/team701/buddymatcher/services/users/UserServiceImplUnitTest.java
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance

#37 Creation of blank AddBuddy endpoint + pairing controller/service
  src/main/java/com/team701/buddymatcher/controllers/pairing/PairingController.java
  src/main/java/com/team701/buddymatcher/dtos/pairing/AddBuddyDTO.java
  src/main/java/com/team701/buddymatcher/services/pairing/PairingService.java
  src/main/java/com/team701/buddymatcher/services/pairing/impl/PairingServiceImpl.java
  src/test/java/com/team701/buddymatcher/controllers/pairing/PairingControllerIntegrationTest.java
Labels: Priority: Medium, Status: Review Needed, Type: Feature

#54 Add Timetable endpoint
  src/main/java/com/team701/buddymatcher/controllers/timetable/TimetableController.java
  src/main/java/com/team701/buddymatcher/domain/timetable/Timetable.java
  src/main/java/com/team701/buddymatcher/dtos/timetable/TimetableDTO.java
  src/main/java/com/team701/buddymatcher/services/timetable/TimetableService.java
  src/main/java/com/team701/buddymatcher/services/timetable/impl/TimetableServiceImpl.java
Labels: Priority: High, Status: Review Needed, Type: Feature

#59 Remove unused import from AddBuddyDTO
  src/main/java/com/team701/buddymatcher/dtos/pairing/AddBuddyDTO.java
Labels: Type: Maintenance

#58 Add User enable/disable pairing endpoint
  src/main/java/com/team701/buddymatcher/controllers/users/UserController.java
  src/main/java/com/team701/buddymatcher/domain/users/Buddies.java
  src/main/java/com/team701/buddymatcher/domain/users/User.java
  src/main/java/com/team701/buddymatcher/dtos/pairing/AddBuddyDTO.java
  src/main/java/com/team701/buddymatcher/dtos/pairing/RemoveBuddyDTO.java
  src/main/java/com/team701/buddymatcher/dtos/users/UserDTO.java
  src/main/java/com/team701/buddymatcher/repositories/users/UserRepository.java
  src/main/java/com/team701/buddymatcher/services/pairing/PairingService.java
  src/main/java/com/team701/buddymatcher/services/pairing/impl/PairingServiceImpl.java
  src/main/java/com/team701/buddymatcher/services/users/UserService.java
  src/main/java/com/team701/buddymatcher/services/users/impl/UserServiceImpl.java
  src/main/resources/schema.sql
  src/test/java/com/team701/buddymatcher/controllers/pairing/PairingControllerIntegrationTest.java
  src/test/java/com/team701/buddymatcher/controllers/users/UserControllerIntegrationTest.java
  src/test/java/com/team701/buddymatcher/controllers/users/UserControllerUnitTest.java
  src/test/java/com/team701/buddymatcher/services/users/UserServiceImplUnitTest.java
  src/test/resources/user_cleanup_data.sql
  src/test/resources/user_data.sql
Labels: Priority: Medium, Status: Review Needed, Type: Feature

#66 Parser for .ics files
  pom.xml
  src/main/java/com/team701/buddymatcher/services/timetable/TimetableService.java
  src/main/java/com/team701/buddymatcher/services/timetable/impl/TimetableServiceImpl.java
Labels: Priority: High, Status: Review Needed, Type: Feature

#70 Change ical4j dependency version from 4.0.0-alpha8 -> 3.2.1
  pom.xml
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#68 Removed the spring fox dependencies and updated swagger
  pom.xml
  src/main/java/com/team701/buddymatcher/SwaggerConfig.java
  src/main/java/com/team701/buddymatcher/controllers/BasicController.java
  src/main/java/com/team701/buddymatcher/controllers/communication/CommunicationController.java
  src/main/java/com/team701/buddymatcher/controllers/pairing/PairingController.java
  src/main/java/com/team701/buddymatcher/controllers/timetable/TimetableController.java
  src/main/java/com/team701/buddymatcher/controllers/users/UserController.java
Labels: Priority: High, Status: Revision Needed

#73 Swagger fix
  pom.xml
  src/main/java/com/team701/buddymatcher/SwaggerConfig.java
  src/main/java/com/team701/buddymatcher/controllers/BasicController.java
  src/main/java/com/team701/buddymatcher/controllers/communication/CommunicationController.java
  src/main/java/com/team701/buddymatcher/controllers/pairing/PairingController.java
  src/main/java/com/team701/buddymatcher/controllers/timetable/TimetableController.java
  src/main/java/com/team701/buddymatcher/controllers/users/UserController.java
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#60 Creation of the course/course-student entities
  src/main/java/com/team701/buddymatcher/BuddyMatcherApplication.java
  src/main/java/com/team701/buddymatcher/domain/timetable/Course.java
  src/main/java/com/team701/buddymatcher/domain/users/User.java
  src/main/java/com/team701/buddymatcher/repositories/timetable/CourseRepository.java
  src/test/java/com/team701/buddymatcher/domain/InMemoryDBIntegrationTest.java
  src/test/resources/application.properties
Labels: Priority: High, Status: Blocked, Type: Feature

#75 Added in new method to TimetableService for populating database
  src/main/java/com/team701/buddymatcher/services/timetable/TimetableService.java
  src/main/java/com/team701/buddymatcher/services/timetable/impl/TimetableServiceImpl.java
  src/test/java/com/team701/buddymatcher/domain/InMemoryDBIntegrationTest.java
  src/test/java/com/team701/buddymatcher/services/timetable/TimetableServiceImplUnitTests.java
Labels: Priority: Medium, Status: Review Needed, Type: Feature, Team: Users

#72 Implement SocketIO for sending and receiving messages
  src/main/java/com/team701/buddymatcher/controllers/communication/CommunicationController.java
  src/main/java/com/team701/buddymatcher/socket/ChatEventHandler.java
  src/main/java/com/team701/buddymatcher/socket/ChatObject.java
  src/main/java/com/team701/buddymatcher/socket/MessageObject.java
Labels: Priority: High, Status: Review Needed, Type: Feature, Team: Communication

#78 Implement getCourses and getCourse endpoint in Timetable controller
  src/main/java/com/team701/buddymatcher/controllers/timetable/TimetableController.java
  src/main/java/com/team701/buddymatcher/domain/timetable/Course.java
  src/main/java/com/team701/buddymatcher/dtos/timetable/CourseDTO.java
  src/main/java/com/team701/buddymatcher/repositories/timetable/CourseRepository.java
  src/main/java/com/team701/buddymatcher/services/timetable/TimetableService.java
  src/main/java/com/team701/buddymatcher/services/timetable/impl/TimetableServiceImpl.java
  src/test/java/com/team701/buddymatcher/controllers/timetable/TimetableControllerIntegrationTest.java
  src/test/java/com/team701/buddymatcher/services/timetable/TimetableServiceImplUnitTests.java
  src/test/resources/timetable_cleanup_data.sql
  src/test/resources/timetable_data.sql
Labels: Type: Feature, Team: Timetable

#87 Testing github actions
  .github/workflows/maven.yml
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#89 Fixing user retrieval from a refactor change
  src/main/java/com/team701/buddymatcher/services/timetable/impl/TimetableServiceImpl.java
  src/test/java/com/team701/buddymatcher/services/timetable/TimetableServiceImplUnitTests.java
Labels: Priority: High, Status: Review Needed, Type: Bug, Team: Users

#88 Added in blank endpoint for 'matchBuddy'
  src/main/java/com/team701/buddymatcher/controllers/pairing/PairingController.java
  src/main/java/com/team701/buddymatcher/dtos/pairing/MatchBuddyDTO.java
  src/main/java/com/team701/buddymatcher/services/pairing/PairingService.java
  src/main/java/com/team701/buddymatcher/services/pairing/impl/PairingServiceImpl.java
  src/test/java/com/team701/buddymatcher/controllers/pairing/PairingControllerIntegrationTest.java
Labels: Priority: Medium, Status: Review Needed, Type: Feature, Team: Pairing

#93 Features/support multiple buddies
  .github/workflows/maven.yml
  src/main/java/com/team701/buddymatcher/BuddyMatcherApplication.java
  src/main/java/com/team701/buddymatcher/controllers/users/UserController.java
  src/main/java/com/team701/buddymatcher/domain/users/Buddies.java
  src/main/java/com/team701/buddymatcher/domain/users/User.java
  src/main/java/com/team701/buddymatcher/dtos/users/UserDTO.java
  src/main/java/com/team701/buddymatcher/repositories/users/BuddiesRepository.java
  src/main/java/com/team701/buddymatcher/repositories/users/UserRepository.java
  src/main/java/com/team701/buddymatcher/services/pairing/impl/PairingServiceImpl.java
  src/main/java/com/team701/buddymatcher/services/users/UserService.java
  src/main/java/com/team701/buddymatcher/services/users/impl/UserServiceImpl.java
  src/test/java/com/team701/buddymatcher/controllers/users/UserControllerIntegrationTest.java
  src/test/java/com/team701/buddymatcher/controllers/users/UserControllerUnitTest.java
  src/test/java/com/team701/buddymatcher/domain/InMemoryDBIntegrationTest.java
  src/test/java/com/team701/buddymatcher/services/pairing/PairingServiceImplUnitTests.java
  src/test/java/com/team701/buddymatcher/services/timetable/TimetableServiceImplUnitTests.java
  src/test/java/com/team701/buddymatcher/services/users/UserServiceImplUnitTest.java
  src/test/resources/timetable_cleanup_data.sql
  src/test/resources/timetable_data.sql
  src/test/resources/user_cleanup_data.sql
  src/test/resources/user_data.sql
Labels: Priority: High, Type: Feature

#79 PR for API Specification (need reviews not ready)
  src/main/java/com/team701/buddymatcher/controllers/communication/Communication.json
Labels: Priority: High, Status: Review Needed, Team: Communication

#95 Implement message repository with methods
  pom.xml
  src/main/java/com/team701/buddymatcher/BuddyMatcherApplication.java
  src/main/java/com/team701/buddymatcher/controllers/communication/CommunicationController.java
  src/main/java/com/team701/buddymatcher/domain/communication/Message.java
  src/main/java/com/team701/buddymatcher/dtos/communication/MessageDTO.java
  src/main/java/com/team701/buddymatcher/repositories/communication/MessageRepository.java
  src/main/java/com/team701/buddymatcher/repositories/users/UserRepository.java
  src/main/java/com/team701/buddymatcher/services/communication/CommunicationService.java
  src/main/java/com/team701/buddymatcher/services/communication/impl/CommunicationServiceImpl.java
  src/main/java/com/team701/buddymatcher/socket/ChatEventHandler.java
  src/main/java/com/team701/buddymatcher/socket/SocketCommandLineRunner.java
  src/main/resources/application.properties
  src/test/java/com/team701/buddymatcher/BuddyMatcherApplicationTests.java
  src/test/java/com/team701/buddymatcher/controllers/communication/CommunicationControllerIntegrationTest.java
  src/test/java/com/team701/buddymatcher/controllers/timetable/TimetableControllerIntegrationTest.java
  src/test/java/com/team701/buddymatcher/controllers/users/UserControllerIntegrationTest.java
  src/test/java/com/team701/buddymatcher/domain/InMemoryDBIntegrationTest.java
  src/test/resources/communication_cleanup_data.sql
  src/test/resources/communication_data.sql
Labels: Priority: High

#98 Add a validate token endpoint
  src/main/java/com/team701/buddymatcher/controllers/users/UserController.java
  src/main/java/com/team701/buddymatcher/controllers/users/ValidateController.java
  src/test/java/com/team701/buddymatcher/controllers/users/ValidateControllerIntegrationTest.java
Labels: Priority: Medium, Status: Review Needed

#97 Implement socketio message store and history with online
  src/main/java/com/team701/buddymatcher/domain/communication/Message.java
  src/main/java/com/team701/buddymatcher/socket/ChatEventHandler.java
  src/main/java/com/team701/buddymatcher/socket/MessageObject.java
  src/main/java/com/team701/buddymatcher/socket/ReadObject.java
  src/main/java/com/team701/buddymatcher/socket/UserObject.java
Labels: Priority: Critical, Status: Review Needed, Team: Communication

#101 Changing the code Owner Paths
  CODEOWNERS
Labels: Priority: Low, Status: Review Needed, Type: Documentation

#99 Implemented logic for matchBuddy and revamped the integration testingt for PairingController
  src/main/java/com/team701/buddymatcher/controllers/pairing/PairingController.java
  src/main/java/com/team701/buddymatcher/repositories/timetable/CourseRepository.java
  src/main/java/com/team701/buddymatcher/services/pairing/PairingService.java
  src/main/java/com/team701/buddymatcher/services/pairing/impl/PairingServiceImpl.java
  src/main/java/com/team701/buddymatcher/services/timetable/TimetableService.java
  src/main/java/com/team701/buddymatcher/services/timetable/impl/TimetableServiceImpl.java
  src/test/java/com/team701/buddymatcher/controllers/pairing/PairingControllerIntegrationTest.java
  src/test/resources/pairing_cleanup_data.sql
  src/test/resources/pairing_data.sql
Labels: Priority: High, Status: Review Needed, Type: Feature, Team: Pairing

#110 Setup Socketio Auth to use JWT token
  src/main/java/com/team701/buddymatcher/socket/ChatEventHandler.java
Labels: Priority: Critical, Type: Feature

#118 Fixed URI encoding in TimetableController.java
  src/main/java/com/team701/buddymatcher/controllers/timetable/TimetableController.java
Labels: Type: Bug

#116 Setup demo data
  src/main/resources/application.properties
  src/main/resources/import.sql
  src/test/java/com/team701/buddymatcher/controllers/communication/CommunicationControllerIntegrationTest.java
  src/test/java/com/team701/buddymatcher/controllers/pairing/PairingControllerIntegrationTest.java
  src/test/java/com/team701/buddymatcher/controllers/timetable/TimetableControllerIntegrationTest.java
  src/test/java/com/team701/buddymatcher/controllers/users/UserControllerIntegrationTest.java
  src/test/resources/cleanup_data.sql
  src/test/resources/import.sql
  src/test/resources/pairing_cleanup_data.sql
  src/test/resources/timetable_cleanup_data.sql
  src/test/resources/user_cleanup_data.sql
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance

#115 Add buddy count to User DTO
  src/main/java/com/team701/buddymatcher/controllers/users/UserController.java
  src/main/java/com/team701/buddymatcher/dtos/users/UserDTO.java
  src/main/java/com/team701/buddymatcher/repositories/BuddiesRepository.java
  src/main/java/com/team701/buddymatcher/repositories/users/UserRepository.java
  src/main/java/com/team701/buddymatcher/services/users/UserService.java
  src/main/java/com/team701/buddymatcher/services/users/impl/UserServiceImpl.java
  src/test/java/com/team701/buddymatcher/controllers/users/UserControllerIntegrationTest.java
  src/test/java/com/team701/buddymatcher/controllers/users/UserControllerUnitTest.java
Labels: Priority: Low, Status: Review Needed, Type: Feature

#120 corrected return type, and added buddycount to returned UserDTO
  src/main/java/com/team701/buddymatcher/controllers/pairing/PairingController.java
  src/main/java/com/team701/buddymatcher/controllers/users/UserController.java
  src/main/resources/import.sql
  src/test/java/com/team701/buddymatcher/BuddyMatcherApplicationTests.java
  src/test/java/com/team701/buddymatcher/controllers/pairing/PairingControllerIntegrationTest.java
Labels: Priority: Low, Status: Review Needed, Type: Maintenance, Team: Pairing

#126 Removal of BasicController/BasicService and moved BuddyRepo
  src/main/java/com/team701/buddymatcher/controllers/BasicController.java
  src/main/java/com/team701/buddymatcher/repositories/users/BuddiesRepository.java
  src/main/java/com/team701/buddymatcher/services/BasicService.java
  src/main/java/com/team701/buddymatcher/services/impl/BasicServiceImpl.java
  src/main/java/com/team701/buddymatcher/services/users/impl/UserServiceImpl.java
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#130 Implement courseBuddy on CourseDTO and SwaggerConfig
  src/main/java/com/team701/buddymatcher/SwaggerConfig.java
  src/main/java/com/team701/buddymatcher/controllers/communication/CommunicationController.java
  src/main/java/com/team701/buddymatcher/controllers/timetable/TimetableController.java
  src/main/java/com/team701/buddymatcher/controllers/users/ValidateController.java
  src/main/java/com/team701/buddymatcher/repositories/communication/MessageRepository.java
  src/main/java/com/team701/buddymatcher/repositories/users/BuddiesRepository.java
  src/main/java/com/team701/buddymatcher/services/communication/CommunicationService.java
  src/main/java/com/team701/buddymatcher/services/communication/impl/CommunicationServiceImpl.java
  src/main/java/com/team701/buddymatcher/services/timetable/TimetableService.java
  src/main/java/com/team701/buddymatcher/services/timetable/impl/TimetableServiceImpl.java
  src/main/java/com/team701/buddymatcher/socket/ChatEventHandler.java
Labels: Priority: Critical, Type: Bug

#134 Move google API client id to environment variables
  src/main/java/com/team701/buddymatcher/controllers/users/UserController.java
Labels: Type: Maintenance

#136 Added GET endpoint for buddies in a course.
  src/main/java/com/team701/buddymatcher/controllers/users/UserController.java
  src/test/java/com/team701/buddymatcher/controllers/users/UserControllerIntegrationTest.java
  src/test/resources/user_data.sql
Labels: Priority: Medium, Status: In Progress, Type: Feature

#141 Endpoint to upload timetable .ics file
  src/main/java/com/team701/buddymatcher/controllers/timetable/TimetableController.java
  src/test/java/com/team701/buddymatcher/controllers/timetable/TimetableControllerIntegrationTest.java
Labels: Priority: Medium, Status: Review Needed, Type: Feature, Team: Timetable
